version: "3"

services:
  db:
    image: postgres:13
    container_name: "postgres-yasuda-page"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
