import { AppBar, Avatar, Box, Button, IconButton, Toolbar, Typography } from '@mui/material'
import { deepOrange } from '@mui/material/colors'
import { Container } from '@mui/system'
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppBar position='fixed' sx={{ background: 'rgba(26,30,46,.5)' }}>
        <Toolbar sx={{ maxWidth: '780px', width: '100%', margin: '0 auto' }}>
          <IconButton size='large' edge='start' color='inherit' aria-label='menu' sx={{ mr: 2 }}>
            <Avatar sx={{ bgcolor: deepOrange[500] }}>K</Avatar>
          </IconButton>
        </Toolbar>
      </AppBar>
      <Container>
        <Typography>Kisuke is a software developer</Typography>
        <Link href={'/'}>Read more</Link>
        <Box sx={{ marginTop: '3rem' }} />
        <Box
          sx={{
            display: 'grid',
            gridTemplateColumns: 'repeat(2,1fr)',
            gap: '1.5rem',
          }}
        >
          <Button
            sx={{
              background: 'linear-gradient(0,#9761a9,#4a4f9c)',
              borderRadius: '22px',
              boxShadow: '0 20px 40px -16px rgba(0,0,0,.4)',
              aspectRatio: '1/1',
              color: 'white',
            }}
          >
            TimeLine
          </Button>
          <Button
            sx={{
              background: 'linear-gradient(-5deg,#479aa5,#5473cb 60%,#3e509d)',
              borderRadius: '22px',
              boxShadow: '0 20px 40px -16px rgba(0,0,0,.4)',
              aspectRatio: '1/1',
              color: 'white',
            }}
          >
            Portfolio
          </Button>
        </Box>
        <Box sx={{ marginTop: '1rem' }} />
        <Box
          sx={{
            display: 'grid',
            gridTemplateColumns: 'repeat(4,1fr)',
            gap: '1.5rem',
          }}
        >
          <Button
            sx={{
              background: 'linear-gradient(144deg,#84d0ff,#19a7ff 50%,#1da1f2 60%,#1a7ee9)',
              borderRadius: '22px',
              boxShadow: '0 20px 40px -16px rgba(0,0,0,.4)',
              aspectRatio: '1/1',
              color: 'white',
            }}
          >
            Twitter
          </Button>
          <Button
            sx={{
              background: 'linear-gradient(144deg,#fff,#c3cbff 60%,#af99ff)',
              borderRadius: '22px',
              boxShadow: '0 20px 40px -16px rgba(0,0,0,.4)',
              aspectRatio: '1/1',
              color: 'white',
            }}
          >
            GitHub
          </Button>
          <Button
            sx={{
              background: 'linear-gradient(144deg,#fff,#b8d3ff 70%,#8fceff)',
              borderRadius: '22px',
              boxShadow: '0 20px 40px -16px rgba(0,0,0,.4)',
              aspectRatio: '1/1',
              color: 'white',
            }}
          >
            Zenn
          </Button>
          <Button
            sx={{
              background: 'linear-gradient(150deg,#acccff,#83a0ff 30%,#9773ff,#e85af9)',
              borderRadius: '22px',
              boxShadow: '0 20px 40px -16px rgba(0,0,0,.4)',
              aspectRatio: '1/1',
              color: 'white',
            }}
          >
            Other
          </Button>
        </Box>
        <Box sx={{ marginTop: '300rem' }} />
      </Container>
    </>
  )
}
